name: .NET development workflow

on: [ push, pull_request ]

jobs:
  build:
    name: ğŸ”¨ Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET Project & dependencies
        uses: ./.github/actions/setup-dotnet-action

      - name: Build
        run: dotnet build --no-restore

      - name: Publish build output
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: |
            ./bin/
            ./**/bin/
            ./**/obj/

  test:
    name: âœ… Test
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET Project & dependencies
        uses: ./.github/actions/setup-dotnet-action

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-output

      - name: Run Tests
        run: dotnet test --no-build --verbosity normal
  lint:
    name: ğŸ§¹ Lint / Format Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET Project & dependencies
        uses: ./.github/actions/setup-dotnet-action

      - name: Format Check
        run: dotnet format --verify-no-changes
  secret:
    name: ğŸ” Read fake secret
    runs-on: ubuntu-latest
    
    steps:
      - name: Read secret
        run: echo "Secret value is ${{ secrets.MY_SECRET }}"